SET_TICKERS = [
    {"symbol": "PTT", "name": "PTT Public Company Limited"},
    {"symbol": "PTTGC", "name": "PTT Global Chemical PCL"},
    {"symbol": "PTTEP", "name": "PTT Exploration and Production PCL"},
    {"symbol": "AOT", "name": "Airports of Thailand PCL"},
    {"symbol": "CPALL", "name": "CP ALL Public Company Limited"},
    {"symbol": "CPF", "name": "Charoen Pokphand Foods PCL"},
    {"symbol": "CP", "name": "Charoen Pokphand Group (CP Group)"},
    {"symbol": "SCC", "name": "The Siam Cement Group PCL"},
    {"symbol": "SCB", "name": "SCB X Public Company Limited"},
    {"symbol": "SCBX", "name": "SCB X Public Company Limited"},
    {"symbol": "KBANK", "name": "Kasikornbank PCL"},
    {"symbol": "BBL", "name": "Bangkok Bank PCL"},
    {"symbol": "KTB", "name": "Krungthai Bank PCL"},
    {"symbol": "KTC", "name": "Krungthai Card PCL"},
    {"symbol": "TMB", "name": "TMBThanachart Bank PCL"},
    {"symbol": "TTB", "name": "TMBThanachart Bank PCL"},
    {"symbol": "ADVANC", "name": "Advanced Info Service PCL"},
    {"symbol": "TRUE", "name": "True Corporation PCL"},
    {"symbol": "DTAC", "name": "Total Access Communication PCL"},
    {"symbol": "INTUCH", "name": "Intouch Holdings PCL"},
    {"symbol": "GULF", "name": "Gulf Energy Development PCL"},
    {"symbol": "GPSC", "name": "Global Power Synergy PCL"},
    {"symbol": "BGRIM", "name": "B.Grimm Power PCL"},
    {"symbol": "EGCO", "name": "Electricity Generating PCL"},
    {"symbol": "RATCH", "name": "Ratch Group PCL"},
    {"symbol": "BCP", "name": "Bangchak Corporation PCL"},
    {"symbol": "IRPC", "name": "IRPC Public Company Limited"},
    {"symbol": "TOP", "name": "Thai Oil PCL"},
    {"symbol": "BANPU", "name": "Banpu Public Company Limited"},
    {"symbol": "BEM", "name": "Bangkok Expressway and Metro PCL"},
    {"symbol": "BTS", "name": "BTS Group Holdings PCL"},
    {"symbol": "CPN", "name": "Central Pattana PCL"},
    {"symbol": "CRC", "name": "Central Retail Corporation PCL"},
    {"symbol": "CENTEL", "name": "Central Plaza Hotel PCL"},
    {"symbol": "MINT", "name": "Minor International PCL"},
    {"symbol": "AWC", "name": "Asset World Corp PCL"},
    {"symbol": "LH", "name": "Land and Houses PCL"},
    {"symbol": "AP", "name": "AP (Thailand) PCL"},
    {"symbol": "SPALI", "name": "Supalai Public Company Limited"},
    {"symbol": "QH", "name": "Quality Houses PCL"},
    {"symbol": "ORI", "name": "Origin Property PCL"},
    {"symbol": "WHA", "name": "WHA Corporation PCL"},
    {"symbol": "HMPRO", "name": "Home Product Center PCL"},
    {"symbol": "GLOBAL", "name": "Siam Global House PCL"},
    {"symbol": "BJC", "name": "Berli Jucker PCL"},
    {"symbol": "BDMS", "name": "Bangkok Dusit Medical Services PCL"},
    {"symbol": "BH", "name": "Bumrungrad Hospital PCL"},
    {"symbol": "BCH", "name": "Bangkok Chain Hospital PCL"},
    {"symbol": "CHG", "name": "Chularat Hospital PCL"},
    {"symbol": "DELTA", "name": "Delta Electronics (Thailand) PCL"},
    {"symbol": "HANA", "name": "Hana Microelectronics PCL"},
    {"symbol": "KCE", "name": "KCE Electronics PCL"},
    {"symbol": "STA", "name": "Sri Trang Agro-Industry PCL"},
    {"symbol": "STGT", "name": "Sri Trang Gloves (Thailand) PCL"},
    {"symbol": "IVL", "name": "Indorama Ventures PCL"},
    {"symbol": "TISCO", "name": "TISCO Financial Group PCL"},
    {"symbol": "SAWAD", "name": "Srisawad Corporation PCL"},
    {"symbol": "MTC", "name": "Muangthai Capital PCL"},
    {"symbol": "TIDLOR", "name": "Ngern Tid Lor PCL"},
    {"symbol": "OSP", "name": "Osotspa Public Company Limited"},
    {"symbol": "CBG", "name": "Carabao Group PCL"},
    {"symbol": "MAKRO", "name": "Siam Makro PCL"},
    {"symbol": "COM7", "name": "COM7 Public Company Limited"},
    {"symbol": "JMT", "name": "JMT Network Services PCL"},
    {"symbol": "EA", "name": "Energy Absolute PCL"},
    {"symbol": "OR", "name": "PTT Oil and Retail Business PCL"},
    {"symbol": "BEAUTY", "name": "Beauty Community PCL"},
    {"symbol": "SINGER", "name": "Singer Thailand PCL"},
    {"symbol": "THANI", "name": "Ratchthani Leasing PCL"},
    {"symbol": "TU", "name": "Thai Union Group PCL"},
    {"symbol": "MAJOR", "name": "Major Cineplex Group PCL"},
    {"symbol": "RS", "name": "RS Public Company Limited"},
    {"symbol": "VGI", "name": "VGI Public Company Limited"},
    {"symbol": "BLA", "name": "Bangkok Life Assurance PCL"},
    {"symbol": "TLI", "name": "Thai Life Insurance PCL"},
    {"symbol": "LANNA", "name": "Lanna Resources PCL"},
    {"symbol": "TPIPP", "name": "TPI Polene Power PCL"},
    {"symbol": "WHAUP", "name": "WHAUP Utilities and Power PCL"},
    {"symbol": "AMATA", "name": "Amata Corporation PCL"},
    {"symbol": "SIRI", "name": "Sansiri Public Company Limited"},
    {"symbol": "SC", "name": "SC Asset Corporation PCL"},
    {"symbol": "PSH", "name": "Pruksa Holding PCL"},
    {"symbol": "NRF", "name": "NR Instant Produce PCL"},
    {"symbol": "JAS", "name": "Jasmine International PCL"},
    {"symbol": "THCOM", "name": "Thaicom Public Company Limited"},
    {"symbol": "FORTH", "name": "Forth Corporation PCL"},
    {"symbol": "JMART", "name": "Jay Mart Group Holdings PCL"},
    {"symbol": "TVO", "name": "Thai Vegetable Oil PCL"},
    {"symbol": "KKP", "name": "Kiatnakin Phatra Bank PCL"},
    {"symbol": "BAM", "name": "Bangkok Commercial Asset Management PCL"},
    {"symbol": "TCAP", "name": "Thanachart Capital PCL"},
    {"symbol": "PLANB", "name": "Plan B Media PCL"},
    {"symbol": "GUNKUL", "name": "Gunkul Engineering PCL"},
    {"symbol": "SUPER", "name": "Super Energy Corporation PCL"},
    {"symbol": "BCPG", "name": "BCPG Public Company Limited"},
    {"symbol": "TTW", "name": "TTW Public Company Limited"},
    {"symbol": "EASTW", "name": "Eastern Water Resources PCL"},
    {"symbol": "MEGA", "name": "Mega Lifesciences PCL"},
    {"symbol": "AU", "name": "Amalgam Universe PCL"},
    {"symbol": "THAI", "name": "Thai Airways International PCL"},
]


def search_set(query: str, max_results: int = 8) -> list:
    q = query.strip().upper()
    if not q:
        return []
    exact = [t for t in SET_TICKERS if t["symbol"] == q]
    prefix = [t for t in SET_TICKERS if t["symbol"].startswith(q) and t["symbol"] != q]
    contains = [t for t in SET_TICKERS if q in t["symbol"] and not t["symbol"].startswith(q)]
    name_match = [t for t in SET_TICKERS if q.lower() in t["name"].lower() and q not in t["symbol"]]
    seen = set()
    out = []
    for item in exact + prefix + contains + name_match:
        if item["symbol"] not in seen:
            seen.add(item["symbol"])
            out.append({"symbol": item["symbol"], "name": item["name"], "exchange": "SET"})
        if len(out) >= max_results:
            break
    return out
